# Tensorflow
TensorFlow is a library for number crunching created and maintained by Google. It’s used mainly for machine learning (especially deep learning) tasks.  It is a symbolic math library that uses dataflow and differentiable programming to perform various tasks focused on training and inference of deep neural networks. It allows developers to create machine learning applications using various tools, libraries, and community resources. Currently, the most famous deep learning library in the world is Google’s TensorFlow. Google product uses machine learning in all of its products to improve the search engine, translation, image captioning or recommendations


#### Installing TensorFlow

In [ ]:
pip install tensorflow

#### Check or setup
Now that we have everything installed. Let’s check that we can import TensorFlow.

In [3]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
tf.__version__

'2.6.0'

#### Tensor
The data type in TensorFlow is Tensor. A scalar is a tensor, a vector is a tensor, a matrix is a tensor, and the matrix of a matrix is a tensor, too. Tensor is a compound type. The elements in Tensor are python basic data types that we are quite familiar with, including bool, int, float, double, string, array.

#### Create Tensors by Python basic types and Numpy array


In [10]:
# int
print(tf.constant(5))
# float
print(tf.constant(5.0))
# double
print(tf.constant(5.0, dtype=tf.float64))
# bool
print(tf.constant(True))
# string
print(tf.constant('hello, world'))
# python list
print(tf.constant([1., 2., 3.]))
# numpy list
print(tf.constant(np.array([1., 2., 3.])))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float64)
tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(b'hello, world', shape=(), dtype=string)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


In [11]:
#tf.convert_to_tensor can also convert other data types to Tensor.
print(tf.constant([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]))
print(tf.convert_to_tensor([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]))

tf.Tensor(
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]], shape=(2, 3), dtype=float32)


#### Create Tensors by tf.random
tf.random.normal: Outputs random values from a normal distribution. The default mean is 0.0. the default standard deviation is 1.0. The shape parameter need to be explicitly assigned.

In [12]:
# tf.random.normal.
print(tf.random.normal([2, 2], mean=0, stddev=1))

tf.Tensor(
[[-0.833465    0.07172389]
 [-0.08796214 -0.9630143 ]], shape=(2, 2), dtype=float32)


In [13]:
# distribution.
print(tf.random.truncated_normal([2,2], mean=0, stddev=1, dtype=tf.double))

tf.Tensor(
[[-0.09857981  0.09909953]
 [ 0.2180097  -0.7462891 ]], shape=(2, 2), dtype=float64)


#### Tensor merge and split
Merging refers to merging multiple tensors into one tensor in a certain dimension. There are two kinds of Merging-concatenation and stacking. Concatenation does not create new dimensions, but stacking creates new dimensions.
The concatenation can be performed on any dimension. The only constraint is that the length of the non-concatenated dimensions must be the same.

In [14]:
a = tf.random.normal([1,2,3])
b = tf.random.normal([2,2,3])
c = tf.concat([a,b], axis=0)
print(c)

tf.Tensor(
[[[-0.14719796 -0.7852111  -0.51880443]
  [ 2.2172763   1.0025381  -1.2630349 ]]

 [[-0.9769671  -1.407355    0.7584211 ]
  [ 1.0559675  -2.052611    1.6925826 ]]

 [[ 0.69797635  0.8376928  -0.4418664 ]
  [ 2.1194541   0.86249673  0.0022708 ]]], shape=(3, 2, 3), dtype=float32)


#### Mathematical operations
TensorFlow 2.x support mathematical operations much more friendly that TensorFlow 1.x. The commonly used operations are listed below. It is clear and absolutely meets python programming habit.

In [15]:
a = tf.constant([[1,2],[3,4]], dtype=tf.float32)
b = tf.constant([[5,6],[7,8]], dtype=tf.float32)
# element-wise add
print(a+b)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)


In [16]:
# element-wise minus
print(a-b)

tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)


In [18]:
# element-wise multipy
print(a*b)
# element-wise divide
print('a/b=', a/b)

tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
a/b= tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)


In [20]:
# maxtrix multipy
print(tf.matmul(a, b))

tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


#### The convolution operation
A convolution operation is a widely used signal-processing technique. For images, convolution is used to produce different effects of an image. An example of edge detection using convolution. This can be achieved by shifting a convolution filter on top of an image to produce a different output at each location. Specifically, at each location we do element-wise multiplication of the elements in the convolution filter with the image patch (same size as the convolution filter) that overlaps with the convolution filter and takes the sum of the multiplication:

In [23]:
#The following is the implementation of the convolution operation:
x = tf.constant( [[
[[1],[2],[3],[4]],
[[4],[3],[2],[1]],
[[5],[6],[7],[8]],
[[8],[7],[6],[5]]
]],
dtype=tf.float32)

x_filter = tf.constant( [
[
[[0.5]],[[1]]
], [
[[0.5]],[[1]]
]
],
dtype=tf.float32)

x_stride = [1,1,1,1]
x_padding = 'VALID'

x_conv = tf.nn.conv2d( input=x, filters=x_filter, strides=x_stride, padding=x_padding)

In [24]:
print(x_conv)

tf.Tensor(
[[[[ 7.5]
   [ 7.5]
   [ 7.5]]

  [[13.5]
   [13.5]
   [13.5]]

  [[19.5]
   [19.5]
   [19.5]]]], shape=(1, 3, 3, 1), dtype=float32)


For the tf.nn.conv2d(…) or tf.keras.layers.conv2d(…) operation, TensorFlow requires input, filter, and stride to be of an exact format. We will now go through each argument in conv2d(input, filter, strides, padding) 

#### The pooling operation
A pooling operation behaves similar to the convolution operation, but the final output is different. Instead of outputting the sum of the element-wise multiplication of the filter and the image patch, we now take the maximum element of the image patch for that location.

In [27]:
x = tf.constant( [[
[[1],[2],[3],[4]],
[[4],[3],[2],[1]],
[[5],[6],[7],[8]],
[[8],[7],[6],[5]]
]],
dtype=tf.float32)

x_ksize = [1,2,2,1]
x_stride = [1,2,2,1]
x_padding = 'VALID'
x_pool = tf.nn.max_pool(input=x, ksize=x_ksize, strides=x_stride, padding=x_padding)

# or for keras
# x_pool_keras = tf.keras.layers.MaxPool2D()(x)

print(x_pool)

tf.Tensor(
[[[[4.]
   [4.]]

  [[8.]
   [8.]]]], shape=(1, 2, 2, 1), dtype=float32)
