# NumPy Basic Operation

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

In [6]:
# Importing NumPy
import numpy as np

In [7]:
# creating an array
array = np.array([1, 2, 3])
print(array)

[1 2 3]


##### Numpy vs. Lists
Numpy and Lists are similar to each other in the sense that they can both store data, be indexed and be iterated. However, Numpy uses less memory, is faster, and more convenient than Lists. Also, we cannot perform calculations (add, subtract, multiply, divide and exponentiation) on Python Lists but we can on Numpy Arrays. For example:

In [9]:
python_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print((python_list) * 2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
numpy_array = np.array([1,2,3,4,5,6,7,8,9])
print((numpy_array)*2)

[ 2  4  6  8 10 12 14 16 18]


#### Another example to show the difference between Lists and Numpy:

In [15]:
print(python_list + python_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [16]:
print(numpy_array + numpy_array)

[ 2  4  6  8 10 12 14 16 18]


#### Finding the size of an array
 the size tool returns how many values are in the array

In [17]:
numpy_array = np.array([1,2,3,4,5,6,7,8,9])
print(numpy_array.size)

9


#### Finding the shape of an array:
The shape tool returns the dimensions of the array in the format (rows, columns). Note: an array can be referred to as a matrix

In [18]:
numpy_matrix = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(numpy_matrix.shape)

(2, 5)


#### Reshaping an array
The reshape tool allows us to change the original dimension of an array. In this example, we changed the array dimensions from (2, 5) to (5, 2)

In [22]:
numpy_matrix = np.array([(1, 2, 3, 4,5), (6, 7, 8,10,11)])
numpy_matrix = numpy_matrix.reshape(5,2)
print(numpy_matrix)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [10 11]]


#### Extracting the special value from an array
This returns the value at a specific position called on. It follows the format [rows, columns] with indexes starting at 0

In [24]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array[2])

3


#### Extracting multiple values from an array
[0, 0:4] returns values from the first row and values from columns with indexes 0 to 3

In [28]:
numpy_array = np.array([(1, 2, 3, 4, 5, 6, 7, 8, 9),(10, 20, 30, 40, 50, 60, 70, 80, 90)])
print(numpy_array[0, 0:4])

[1 2 3 4]


#### Reversing the order of an array
“ ::-1 ” in the rows position reverses the order of the rows whereas “ ::-1 ” in the columns position reverses the order of values in the columns

In [31]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array[::-1])

[9 8 7 6 5 4 3 2 1]


#### Finding the max, min and sum of an array:


In [38]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# To find out the max value from the array
print(numpy_array.max())

9


In [36]:
# To find out the minimum value of the array
print(numpy_array.min())

1


In [37]:
# To find out the sum
print(numpy_array.sum())

45


#### Finding the mean, median, variance and standard deviation of an array:

In [43]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# To find out the mean
print(numpy_array.mean())

# To find out the median

print(np.median(numpy_array))

# To find out the variance
print(numpy_array.var())

# TO find out the standard deviation
print(numpy_array.std())

5.0
5.0
6.666666666666667
2.581988897471611


#### Doing an operation on a row and column:
"axis = 0" performs an operation on each y-axis within the array. "axis = 1" performs an operation on each x-axis within the array. "axis = None" performs an operation on all values in the array, it is defaul

In [44]:
print(numpy_matrix)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [10 11]]


In [45]:
print(numpy_matrix.sum(axis = 0))

[26 31]


In [46]:
print(numpy_matrix.sum(axis = 1))

[ 3  7 11 15 21]


In [47]:
print(numpy_matrix.sum(axis = None))

57


#### Joining arrays together to create one array
The concatenate tool joins arrays together. The final array can be reshaped by performing operations on specific axes

In [48]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_3 = np.array([7,8,9])
print(np.concatenate((array_1, array_2, array_3)))

[1 2 3 4 5 6 7 8 9]


In [50]:
array_4 = np.array([[1,2,3],[0,0,0]])
array_5 = np.array([[0,0,0],[7,8,9]])
print(np.concatenate((array_1, array_2), axis = 0))

[1 2 3 4 5 6]


#### Printing identity matrices
In the first example, the identity tool returns a square matrix with the dimensions 3 by 3. In the second example, the eye tool prints an 8 by 7 matrix with the first upper diagonal shifted one over denoted with k = 1

In [51]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
print(np.eye(8, 7, k = 1))  

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### Multiplying matrices
The dot tool returns the dot products of two arrays. The cross tool returns the cross product of two arrays

In [54]:
array_1 = np.array([1,2])
array_2 = np.array([3,4])

print(np.dot(array_1,array_2))
print(np.cross(array_1,array_2))

11
-2


#### Creating array data


In [56]:
# Creating an array from 0 to 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [57]:
# Creating an array of floats
arr = np.arange(10.1)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [58]:
# The first and second arguments specify the start and end points
arr = np.arange(-5, 5)
print(arr)

[-5 -4 -3 -2 -1  0  1  2  3  4]


In [59]:
# Third argument specifies the step
arr = np.arange(-10, 10, 4)
print(arr)

[-10  -6  -2   2   6]
